bonitasoft/bonita-application-directory

applications/bonita-application-directory.xml
pom.xml

covers [RUNTIME-110](https://bonitasoft.atlassian.net/browse/RUNTIME-110)

feat(application): Use the correct page and layout

---

applications/bonita-application-directory.xml
pom.xml

Covers [RUNTIME-163](https://bonitasoft.atlassian.net/browse/RUNTIME-163)

feat (application directory): Add error pages into the application directory

---

pom.xml

this is a artifact in itself, also declare dependencies on the pages in order to let consumers of that artifact be able to retrieve all pages required
Relates to [RUNTIME-183](https://bonitasoft.atlassian.net/browse/RUNTIME-183)

feat: publish xml of the application

---

pom.xml
zip-with-resources-assembly.xml

* add new zip with resources package including the built version of the application pages
Covers [RUNTIME-263](https://bonitasoft.atlassian.net/browse/RUNTIME-263)

feat(packaging): add new zip with resources package

---

applications/bonita-application-directory.xml
bonita-distrib/bonita-application-directory.xml

covers [RUNTIME-263](https://bonitasoft.atlassian.net/browse/RUNTIME-263)

feat(packaging): use internal profile ALL

---

applications/bonita-application-directory.xml
bonita-distrib/bonita-application-directory.xml

Relates to [RUNTIME-366](https://bonitasoft.atlassian.net/browse/RUNTIME-366)

feat: add description to the application

---

infrastructure/change_version.sh

exclude bos-distrib folders when changing the release version

 fix(release): update change version script

---

bos-distrib/applications/bonita-application-directory.xml

covers [RUNTIME-987](https://bonitasoft.atlassian.net/browse/RUNTIME-987)
relates to [#3](https://github.com/bonitasoft/bonita-web-pages-sp/pull/3)

Update app directory version

---

bos-distrib/applications/bonita-application-directory.xml
pom.xml

Covers [DEV-220](https://bonitasoft.atlassian.net/browse/DEV-220)
Depends on bonitasoft/bonita-web-pages-sp/pull/218
[DEV-220]: https://bonitasoft.atlassian.net/browse/DEV-220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(update pages versions): follow bonita-web-pages updates

---

bos-distrib/applications/bonita-application-directory.xml

covers [RUNTIME-1364](https://bonitasoft.atlassian.net/browse/RUNTIME-1364)
relates to [#255](https://github.com/bonitasoft/bonita-web-pages-sp/pull/255)
[RUNTIME-1364]: https://bonitasoft.atlassian.net/browse/RUNTIME-1364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(app directory): update page version

---

bonita-distrib/bonita-application-directory.xml
bos-distrib/applications/bonita-application-directory.xml
pom.xml

Covers [DEV-477](https://bonitasoft.atlassian.net/browse/DEV-477)
[DEV-477]: https://bonitasoft.atlassian.net/browse/DEV-477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat (app directory): add 503 error page

---

pom.xml
src/main/resources/bos-distrib/applications/bonita-application-directory.xml

Covers [DEV-524](https://bonitasoft.atlassian.net/browse/DEV-524)
Depends on bonita-web-pages-sp PR to update app directory
[DEV-524]: https://bonitasoft.atlassian.net/browse/DEV-524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(maintenance mode): update app directory version

---

bos-distrib/applications/bonita-application-directory.xml

Covers [RUNTIME-1806](https://bonitasoft.atlassian.net/browse/RUNTIME-1806)
[RUNTIME-1806]: https://bonitasoft.atlassian.net/browse/RUNTIME-1806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat (application directory): update page version

---

bos-distrib/applications/bonita-application-directory.xml

Covers [RUNTIME-1806](https://bonitasoft.atlassian.net/browse/RUNTIME-1806)
[RUNTIME-1806]: https://bonitasoft.atlassian.net/browse/RUNTIME-1806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat (application directory): update application page version

---

src/main/resources/bos-distrib/applications/bonita-application-directory.xml

Relates to [RUNTIME-1829](https://bonitasoft.atlassian.net/browse/RUNTIME-1829)
[RUNTIME-1829]: https://bonitasoft.atlassian.net/browse/RUNTIME-1829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(application directory): follow version update

---

.github/workflows/_reusable_build.yml
.github/workflows/build_pr.yml

Covers [CI-859](https://bonitasoft.atlassian.net/browse/CI-859)
Covers [CI-860](https://bonitasoft.atlassian.net/browse/CI-860)
[CI-859]: https://bonitasoft.atlassian.net/browse/CI-859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CI-860]: https://bonitasoft.atlassian.net/browse/CI-860?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore (CI) migrate build github actions

---

.github/workflows/all_check_passed.yml

Related to [CI-865](https://bonitasoft.atlassian.net/browse/CI-865)
[CI-865]: https://bonitasoft.atlassian.net/browse/CI-865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ci(github): add all checks pass workflow

---

.github/workflows/create_merge_pr_upstream.yml

Covers [CI-865](https://bonitasoft.atlassian.net/browse/CI-865)
[CI-865]: https://bonitasoft.atlassian.net/browse/CI-865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ci(merge): workflow to create merge pr upstream

---

.github/workflows/_reusable_build.yml

Also remove the upload bos step as it is already pushed on JFrog

ci(build): fix incomplete maven deploy

---

src/main/resources/bos-distrib/pom.xml

chore(merge): resolve conflicts

---

.github/workflows/_reusable_tag.yml

Covers [CI-862](https://bonitasoft.atlassian.net/browse/CI-862)
[CI-862]: https://bonitasoft.atlassian.net/browse/CI-862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI(tag): reusable tag

---

src/main/resources/bos-distrib/applications/bonita-application-directory.xml

Related to https://github.com/bonitasoft/bonita-web-pages-sp/pull/486

feat(app_directory_update): Update application directory page name

---

pom.xml

Update app version
Related to bonitasoft/bonita-web-pages-sp#486

 feat(app_directory_update): Update application directory

---

pom.xml
src/main/resources/bos-distrib/applications/bonita-application-directory.xml

Covers [PROD-345](https://bonitasoft.atlassian.net/browse/PROD-345)
[PROD-345]: https://bonitasoft.atlassian.net/browse/PROD-345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat (page update): update application version
